apiVersion: apps/v1
kind: Deployment 
metadata:
  name: payment-db-deply
spec:
 replicas: 1
 selector:
   matchLabels:
    app: payment-db 
 template:
   metadata:
     labels:
       app: payment-db 
   spec:
     containers:
       - name: payment-container 
         image: mongo 
---
apiVersion: v1 
kind: Service 
metadata:
  name:  payment-db-service
spec:
  selector:
    app: payment-db
  ports:
    - name: payment-port 
      port: 27017 
      targetPort: 27017 
      protocol: TCP




    