apiVersion: skaffold/v4beta2
kind: Config 
metadata:
  name:  payment

build:
  local:
    push: false 
  artifacts:
    - image: diwa1214/dev
      context: ../payment
      docker: 
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - ./infra/k8s/*
