apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ticket-deploy
spec:
  replicas: 1
  selector:
     matchLabels:
       app: ticket-app
  template:
     metadata:
       labels:
         app: ticket-app
     spec:
       containers:
         - name: ticket-app-container
           image: diwa1214/dev:ticketimage
           env:
            - name: JWTAUTH
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
            - name:  MONGO_URI
              value: 'mongodb://ticket-db-service/ticket'
          
            - name:  CLUSTER_ID
              value: 'ticketing' 

            - name:  NATS_URL
              value: 'https://nats-streaming-service:4222'

            - name:  CLIENT_ID
              valueFrom:
               fieldRef:
                 fieldPath: metadata.name
---

apiVersion: v1 
kind: Service 
metadata:
  name:  ticket-service
spec:
  selector:
    app: ticket-app
  ports:
  - name:  ticket-srv-port
    port:  5000
    protocol: TCP
    targetPort: 5000


