apiVersion: apps/v1
kind: Deployment 
metadata:
  name: order-db-deply
spec:
 replicas: 1
 selector:
   matchLabels:
    app: order-db 
 template:
   metadata:
     labels:
       app: order-db 
   spec:
     containers:
       - name: order-container 
         image: mongo 
---
apiVersion: v1 
kind: Service 
metadata:
  name:  order-db-service
spec:
  selector:
    app: order-db
  ports:
    - name: order-port 
      port: 27017 
      targetPort: 27017 
      protocol: TCP




    